# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e209044840de6d341d72cf7b4fc33dac4dcfcf16bb0b6c8c9559fff9d2fd5728dbff9fc7dca525c44848ef391421384b8cff2b02866a214363b60ba9e42f09c2

test:
  secret_key_base: 6a716b1cfa72aaad897558c4feb0dad360535f1fe7186ed2c9de4f6f499703410176cb4222e85a22ec8e61de11212848db683a7a443ab7e7b2c14cc691a079f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
